version: '3.7'

networks:
  mysql-network:

services:
  mysqldb:
    restart: always
    image: mysql:8
    container_name: mysqldb
    networks:
        - mysql-network
    environment:
      MYSQL_DATABASE: world_of_manga
      MYSQL_USER: worldOfManga
      MYSQL_PASSWORD: worldOfManga
      MYSQL_ROOT_PASSWORD: worldOfManga
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3366:3306
    healthcheck:
      test: "/usr/bin/mysql --user=worldOfManga --password=worldOfManga--execute \"SHOW DATABASES;\""
  app:
    restart: on-failure
    build: ./
    networks:
        - mysql-network
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - mysqldb