version: '3.7'

services:
  world_of_manga:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.99.100:3366/world_of_manga?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
      - SPRING_DATASOURCE_USERNAME=worldOfManga
      - SPRING_DATASOURCE_PASSWORD=worldOfManga
  mysql:
    restart: always
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: world_of_manga
      MYSQL_USER: worldOfManga
      MYSQL_PASSWORD: worldOfManga
      MYSQL_ROOT_PASSWORD: worldOfManga
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3366:3306
    healthcheck:
      test: "/usr/bin/mysql --user=worldOfManga --password=worldOfManga--execute \"SHOW DATABASES;\""