# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
  
    branches:
        only:
          - master
  
    docker:

      - image: circleci/openjdk:11.0.1-jdk
        environment:
          JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/world_of_manga
          JDBC_DATABASE_USERNAME: postgres
          JDBC_DATABASE_PASSWORD:
        
      - image: postgres:9.6
        environment:
          POSTGRES_DB: world_of_manga
         
    working_directory: ~/world_of_manga

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


      - run: mvn test