# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:

      - image: circleci/openjdk:11.0.1-jdk
        environment:
        JDBC_DATABASE_URL: jdbc:mysql://localhost:3366/world_of_manga?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
        JDBC_DATABASE_USERNAME: root
        JDBC_DATABASE_PASSWORD: root
        
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
        POSTGRES_DB: world_of_manga
         

    working_directory: ~/world_of_manga

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout


      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


      - run: mvn test